### PR TITLE
Optimise and refactor

### PR DESCRIPTION
**Pull request by Billlynch**
This does things like only generate the tree to a depth of one if the game is in a terminal state. 
It also executes the heuristics in parallel using the stream API. (SAFE).
Plus a slight refactor.

### CODE REVIEW

**Review by nathan92 — DISMISSED** [review]
Works locally, all code looks good to me 👍

**Review by Samrobbo — DISMISSED** [review]
Approving, but concurrent has occured.

**Review by Pritchy96 — CHANGES_REQUESTED** [review]

**Review by Samrobbo — DISMISSED** [review]
LGTM

**Review by Pritchy96 — DISMISSED** [review]

**Comment by Pritchy96** [comment]
Closing - Project is finished.

**Pull request closed without merging**
